
app_name: 'testModule'
project_name: 'testProject'
project_version: '0.1'

logging:
  level: DEBUG
  format: '%(levelname)s %(asctime)s  %(message)s'
  message_format: '%(project_name)s:%(project_version)s %(app_id)s %(_filename)s:%(_lineno)d [%(tags)s] '

  filters:
    trans:
      tag: 'TRANS:'   # tag 过滤
  handlers:
    - type: file
      enable: true
      filename: 'server.log'
      encoding: 'UTF-8'
      max_bytes: 67108864 # 64MB
      backup_count: 10

    - type: console
      enable: true



http_trace: #自动日志记录
  level: DEBUG
  request:
    options:
      header:  false
      body:  true
      max_size: 500 # 最大数据包长度
    urls:
      - match: '/'
      - match: 'zoo/cat'
        body:  true

  response:
    options:
      header:  false
      body:  true
      max_size: 500 # 最大数据包长度
    urls:
      - match: '/'
      - match: 'zoo/cat'
        body:  true



datasources:
  - name: 'mongodb'
    class: 'mantis.fundamental.nosql.mongo.Datasource'
    host: 'mongodb'
    port: 27017
    dbname:
    user:
    password:
    enable: true

  - name: 'zk_1'
    type: 'zookeeper'
    enable: false
    hosts: 'localhost:2181'
    root: '/camel'

  - name: 'redis'
    class: 'mantis.fundamental.redis.datasource.Datasource'
    host: 'redis'
    port: 6379
    password: ''
    db: 0
    enable: true

message_brokers:
  - name: 'kafka_1'
    class: 'mantis.fundamental.kafka.MessageBroker'
    enable: false
    hosts: 'localhost:9092'
    zookeepers: 'localhost:2181'
    channels:
      - name: 'test'
        group: 'abcdef'  # simple_consumer if group is null
        handler:  'access.kafka.test.get_message' # last unit< get_message> is function object
        enable: true
        type: 'queue'

  - name: 'redis'
    class: 'mantis.fundamental.redis.broker.MessageBroker'
    host: 'redis'
    port: 6379
    password: ''
    db: 0
    enable: true
    channels:
      - name: 'ctp_contract_tick_queue'
#        handler: 'get_message'
        enable: true
        type: 'queue' # or queue

services:
  - name: 'http'
    class: 'mantis.fundamental.flask.service.FlaskService'
    enable: true
    block: false
    cfgs:
      SQLALCHEMY_DATABASE_URI : 'sqlite:////tmp/test.db'
      SQLALCHEMY_BINDS:
      SQLALCHEMY_TRACK_MODIFICATIONS : true
      SQLALCHEMY_COMMIT_ON_TEARDOWN : true
      SECRET_KEY : "abc"
      TEMPLATES_AUTO_RELOAD: true
      DEBUG: true
      SEND_FILE_MAX_AGE_DEFAULT: 0
    http:
#      host : '172.16.109.237'
      host : ''
      port : 19002
      threaded: false
      debug: true

    blueprints:
      - package: 'http'
        url: '/'
        name: 'http'
        register: true
        modules:
          - name: 'views'
            url: 'console'
            routes:
              - url: '/'                    # url name
                name: 'index'   # function name
                methods: 'GET'
          - name: 'api'
            url: 'api'
            routes:
              - url: '/device/actives'                    # url name
                name: 'get_active_devices'   # function name
                methods: 'GET'
              - url: '/command'
                name: 'send_command'
                methods: 'POST'

  - name:       'main'
    id:     'location-adapter'
    enable:     true
    class:      'main.MainService'
    table_name_lbs_cell: 'lbs_cell'
    fanout:
      - name: 'switch0'
        channels:
          - 'redis/blue_earth.device.message.queue/queue'
          - 'redis/blue_earth.device.message.pub/pubsub'

      - name: 'data-location'
        channels:
          - 'redis/blue_earth.device.location.queue/queue'

      - name: 'logging'
        channels:
          - 'redis/trade.log.{service_type}/queue'
          - 'redis/trade.log.{service_type}.{service_id}/pubsub'
      - name: 'strategy_logging'
        channels:
          - 'redis/trade.strategy.log/queue'
          - 'redis/trade.strategy.log.pub/pubsub'
    lbs_ak: '0b7d114fdc4eb50079408292b7249015'
    lbs_web_ak: 'c0c74a14f8b411cc5433e8946bf82377'
    audio_path: '/tmp/audio'
    access_command_url: 'http://localhost:19002/api/command'
    servers:
      - name: 'concox-server-gt03'
        enable: true
        host: ''
        port: 25002
        accumulator:
          class: 'mantis.BlueEarth.vendor.concox.gt03.accumulator.DataAccumulator'
        handler:
          class: 'handlers.concox_gt03.DataAdapter'
          device_type: 'gt03'
          sequence_key: 'blue_earth.device.sequence.gt03'
          command_controller: 'mantis.BlueEarth.vendor.concox.gt03.command.CommandController'

      - name: 'concox-server-gt310'
        enable: ture
        host: ''
        port: 25003
        accumulator:
          class: 'mantis.BlueEarth.vendor.concox.gt310.accumulator.DataAccumulator'

        handler:
          class: 'handlers.concox_gt310.DataAdapter'
          device_type: 'gt310'
          sequence_key: 'blue_earth.device.sequence.gt310'
          command_controller: 'mantis.BlueEarth.vendor.concox.gt310.command.CommandController'

      - name: 'concox-server-ev25'
        enable: true
        host: ''
        port: 25004
        accumulator:
          class: 'mantis.BlueEarth.vendor.concox.ev25.accumulator.DataAccumulator'
        handler:
          class: 'handlers.concox_ev25.DataAdapter'
          device_type: 'ev25'
          sequence_key: 'blue_earth.device.sequence.ev25'
          command_controller: 'mantis.BlueEarth.vendor.concox.ev25.command.CommandController'






# qpid-receive -b localhost:5672 -a "mq_test;{create:always,node:{type:queue,durable:true}}"






